### ISSUE TITLE
Missing documentation about how to participate with developement

### ISSUE THREAD

**Issue by leoroj** [rojeras/tpinfo-frontend#2]
The README must be updated with a section which describes how to use github and pull requests to participate in development efforts.

**Comment by rojeras** [comment]
Good idea. Can you fix it?

**Comment by leoroj** [comment]
Sure

**Comment by leoroj** [comment]
OK, I will make a branch out of develop and write it there.

**Comment by rojeras** [comment]
Your issue has been accepted and merged into `develop`.
