### ISSUE TITLE
Filtering of contracts and domains give strange result

### ISSUE THREAD

**Issue by rojeras** [rojeras/tpinfo-frontend#28]
Jo, jag kan hålla med om att det ser märkligt ut. Jag sätter upp det på backloggen.

Tack för påpekandet!

MvH/LEO

On Mon, Nov 22, 2021 at 8:19 AM Mårtensson Andreas <Andreas.Martensson@inera.se> wrote:
Hejsan,

 

Ok, då är jag med på att den söker både på kontrakt och domän. Men, som du skriver nedan, att när det blir träff på ett domännamn så presenteras alla kontrakt i domänen. Borde det inte då presenteras i sin ”egen” domän?

I bilden nedan blandas kontrakt från olika domäner under infrastructure:ititegration:registry och  ititegration:registry. De kontrakt som inte tillhör dessa domäner borde väl presenteras under sin egen domän?

 

/Andreas

 

Från: Lars Erik Röjerås <lars.erik.rojeras@skoview.se>
Skickat: den 21 november 2021 16:51
Till: Mårtensson Andreas <Andreas.Martensson@inera.se>
Ämne: Re: knas i sökning i HIPPO

 

Hej,

 

Det är en effekt av att sökning går på både kontrakts- och domännamn. Och när det blir träff på ett domännamn visas även alla de kontrakt som ingår i domänen. 

 

Man kan diskutera om det är bra. 😏

 

On Tue, Nov 16, 2021 at 12:34 PM Mårtensson Andreas <Andreas.Martensson@inera.se> wrote:

Hej,

 

När jag skriver ”reg” i sökfältet för Kontrakt/Domän så får jag svar enligt bilden nedan. Kontrakt från olika domäner blandas, se infrastructure:itintegration:registry och itintegration:registry
![Screenshot_2021-11-22_08-24-12](https://user-images.githubusercontent.com/13849102/142820198-1b9293c8-f279-4311-a88f-a12025e8a0b8.png)

**Comment by Marie-LouiseAndersson** [comment]
By design.
